<main id="main" class="main">

    <div class="pagetitle">
        <h1>HappyMemories</h1>
        <nav>
            <ol class="breadcrumb">
<li class="breadcrumb-item"><a href="<?= BASE_URL ?>"index>Home</a></li>                <li class="breadcrumb-item active">Buscar</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
        <div class="row">
            <div class="card">
                <div class="card-header">
                    <center>
                        <h4 class="card-header">Busqueda de Ubicacion de descanso</h4>
                    </center>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-center pt-3">
                        <!-- Button trigger modal -->
                        <div class="form-group col-lg-12">
    <label for="buscar">Ingrese Nombre de la persona que desea buscar</label>
    <input type="text" class="form-control" id="buscar" placeholder="Ingrese nombre de la persona">

    
  </div>
                    </div>


                </div>
                <div class="card-body mt-5">

                    <table id="table" class="display">
                        <thead>
                            <th>Foto</th>
                            <th>Nombre Completo</th>
                            <th>Fecha que Nacio</th>
                            <th>Fecha Defunción</th>
                          

                            <th>Acción</th>
                        </thead>
                        <tbody>
                           
                        </tbody>

                    </table>

                </div>
            </div>
        </div>

    </section>



     <!-- Modal  para agregar Departamento-->
     <div class="modal fade" id="modalPerfilBuscar" tabindex="-1" 
        aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
                <div class="modal-header" style="background-color:#ecc006;color:#FFF">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Perfil de Información y recuerdos</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">

                


                    






                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal"><i class="fa-solid fa-xmark"></i>
                        Cerrar</button>
                   
                </div>

                </form>
            </div>
        </div>
    </div>

    

    



</main>


