<main id="main" class="main">

    <div class="pagetitle">
        <h1>HappyMemories</h1>
        <nav>
            <ol class="breadcrumb">
<li class="breadcrumb-item"><a href="<?= BASE_URL ?>"index>Home</a></li>                <li class="breadcrumb-item active">Servicios</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
        <div class="row">
            <div class="card">
                <div class="card-header">
                    <center>
                        <h4 class="card-header">Registro y Listado de Servicios Ofrecidos</h4>
                    </center>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end pt-3">
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                            data-bs-target="#modalAgregarServicio">
                            <i class="fa-solid fa-plus"></i> Agregar Nuevo
                        </button>
                    </div>


                </div>
                <div class="card-body mt-5">

                    <table id="table" class="display">
                        <thead>
                            <th>ID Servicio</th>
                            <th>Tipo Servicio</th>
                            <th>Descripción</th>
                            <th>Precio</th>

                            <th>Acción</th>
                        </thead>
                        <tbody>
                            <?= $this->tabla ?>
                        </tbody>

                    </table>

                </div>
            </div>
        </div>

    </section>




    <!-- Modal  para agregar Departamento-->
    <div class="modal fade" id="modalAgregarServicio" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false"
        aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header" style="background-color:#ecc006">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Agregar Nuevo Servicio</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <form class="row" method="post" id="formAgregarServicio" enctype="multipart/form-data">

                            <div class="mb-3 col-lg-12">
                                <label for="" class="form-label">Tipo de Servicio</label>
                                <select class="form-select" name="tipoServicio" id="tipoServicio">
                                    <option value="Limpieza">Seleccione una Opción</option>
                                    <option value="Limpieza">Limpieza</option>
                                    <option value="Reparación">Reparación</option>
                                    <option value="Pintura">Pintura</option>
                                    <option value="Mantenimiento General">Mantenimiento General</option>
                                    <option value="Monumento Personalizado">Monumento Personalizado</option>
                                    <option value="Floristería">Floristería</option>
                                    <option value="Servicios de Grabado">Servicios de Grabado</option>
                                    <option value="Mantenimiento de Jardines">Mantenimiento de Jardines</option>
                                    <option value="Personalizado">Personalizado</option>
                                </select>
                            </div>

                            <div class="mb-3 col-lg-12">
                                <label for="" class="form-label">Descripción</label>
                                <textarea class="form-control" name="descripcionServicio"
                                    id="descripcionServicio"></textarea>
                            </div>

                         
                            <div class="mb-3 col-lg-12">
                                <div class="input-group">
                                    <span class="input-group-text">C$</span>
                                    <input type="text" id="precioServicio" name="precioServicio" class="form-control" required>
                                    <span class="input-group-text">.00</span>
                                </div>
                            </div>

                            <div class="mb-3 col-lg-12">
                                <label for="" class="form-label">Imagen Servicio</label>
                                <input type="file" class="form-control" id="imagenServicio" name="imagenServicio"
                                    required>
                            </div>


                    </div>






                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal"><i class="fa-solid fa-ban"></i>
                        Cancelar</button>
                    <button type="submit" style="color:#fff" class="btn btn-warning"><i class="fa-solid fa-plus"></i> Agregar
                        Registro</button>
                </div>

                </form>
            </div>
        </div>
    </div>

    



</main>