<main id="main" class="main">

  <div class="pagetitle">
    <h1>HappyMemories</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="index.html">Home</a></li>
        <li class="breadcrumb-item active">Dashboard</li>
      </ol>
    </nav>
  </div><!-- End Page Title -->

  <section class="section dashboard">


    <section class="container my-5">
      <div class="row align-items-center">
        <!-- Columna de la imagen -->
        <div class="col-md-5">
          <img sRc='<?= PLANTILLA ?>assets/img/logoColor.png' alt="Imagen de bienvenida"
            class="img-fluid rounded shadow-lg">
        </div>

        <!-- Columna del texto -->
        <div class="col-md-7">
          <h1 class="display-4 fw-bold">Bienvenidos a Happy Memories</h1>
          <p class="lead">
            Recordamos a nuestros seres queridos de una manera única. <br>
            Aquí podrás conservar sus recuerdos y compartir momentos especiales con tus amigos y familiares.
          </p>
          <p class="fs-5">
            Explora historias, fotos, y testimonios que honran la memoria de quienes dejaron una huella imborrable en
            nuestras vidas.
          </p>
        </div>
      </div>
    </section>

    <!-- Titulo principal -->


    <div class="row">
      <div class="col-lg-12">
        <div class="row">
          <!-- Sales Card -->
          <div class="col-xxl-4 col-md-6">
            <div class="card info-card sales-card">



              <div class="card-body">
                <h5 class="card-title">Numero de Productos <span>@ MercApp</span> </h5>

                <div class="d-flex align-items-center">
                  <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                    <i class="fa-solid fa-photo-film"></i>
                  </div>
                  <div class="ps-3">
                    <h6><?= $this->productos ?></h6>


                  </div>
                </div>
              </div>

            </div>
          </div><!-- End Sales Card -->

          <!-- Revenue Card -->
          <div class="col-xxl-4 col-md-6">
            <div class="card info-card revenue-card">
              <div class="card-body">
                <h5 class="card-title">Numero de dueños de negocio <span>@ MercApp</span> </h5>

                <div class="d-flex align-items-center">
                  <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                    <i class="fa-solid fa-monument"></i>
                  </div>
                  <div class="ps-3">
                    <h6><?= $this->propietarios ?></h6>


                  </div>
                </div>
              </div>

            </div>
          </div><!-- End Revenue Card -->

          <!-- Revenue Card -->
          <div class="col-xxl-4 col-md-6">
            <div class="card info-card revenue-card">
              <div class="card-body">
                <h5 class="card-title">Monto en ventas realizadas <span>@ MercApp</span> </h5>

                <div class="d-flex align-items-center">
                  <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                    <i class="fa-solid fa-bell-concierge"></i>
                  </div>
                  <div class="ps-3">
                    <h6>C$ 5000</h6>


                  </div>
                </div>
              </div>

            </div>
          </div><!-- End Revenue Card -->




        </div><!-- Fin de la fila -->
      </div><!-- fin columnas grid -->
    </div><!-- fin de la fila -->


  

    <!-- Inicio mision y vision -->
    <div class="row">
      <div class="card">
        <div class="card-header">
          <center>
            <h1 class="card-title">Sobre Nosotros</h1>
          </center>
        </div>

        <div class="card-body ">
          <div class="row align-items-top">
            <div class="col-lg-6">
              <!-- Default Card -->
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Nuestra Misión</h5>
                  "Happy Memories" tiene como misión proporcionar un espacio digital significativo y accesible para la
                  conmemoración y preservación de las memorias de los seres queridos que han fallecido. A través de un
                  sistema web intuitivo, buscamos ofrecer a las alcaldías una herramienta eficaz para el registro de
                  defunciones, mientras que proporcionamos a las familias y amigos un entorno seguro y enriquecedor
                  donde puedan compartir recuerdos, ver y gestionar información sobre las tumbas y mantener el legado de
                  sus seres queridos vivos a través de un mapa interactivo. Además, facilitamos servicios de
                  mantenimiento para garantizar que los lugares de descanso reciban el cuidado adecuado, ofrecer un
                  servicio valioso tanto a las familias como a las alcaldías. Se enfoca en la preservación de la memoria
                  de los fallecidos y en la eficiencia administrativa, reflejando el compromiso del proyecto con la
                  conmemoración digna y la gestión adecuada de las defunciones.
                </div>
              </div><!-- End Default Card -->
            </div>

            <div class="col-lg-6">
              <!-- Default Card -->
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Nuestra Visión</h5>
                  "Nuestra visión en 'Happy Memories' es convertirnos en la plataforma líder en conmemoración digital,
                  expandiendo nuestras funcionalidades para incluir experiencias virtuales y servicios integrales que
                  atiendan las necesidades de los usuarios en todo el país y más allá. Aspiramos a ser el referente en
                  la preservación de memorias y el cuidado de tumbas, proporcionando un entorno que no solo facilite la
                  gestión administrativa para las alcaldías, sino que también brinde paz y consuelo a las familias al
                  asegurar que las memorias de sus seres queridos sean honradas y mantenidas con el mayor respeto y
                  dignidad. Nos comprometemos a innovar constantemente para ofrecer soluciones que conecten a las
                  personas con sus recuerdos de manera significativa y accesible."
                </div>
              </div><!-- End Default Card -->
            </div>



          </div>


        </div>






      </div>
    </div><!-- Fin mision y vision  -->


    <!-- Inicio Servicios -->
    <div class="row">
      <div class="card">
        <div class="card-header">
          <center>
            <h1 class="card-title">SERVICIOS QUE OFRECEMOS</h1>
          </center>
        </div>
        <div class="card-body mt-5">


          <div id="contenedor-cards" class="row"> </div>


        </div>






      </div>
    </div><!-- Fin Servicios -->

    <!-- Inicio Servicios -->
    <div class="row">
      <div class="card">
        <div class="card-header align-items-center">

          <div class="d-flex justify-content-center align-items-center">
            <h1 class="card-title me-2">CONTACTA CON HAPPY MEMORIES</h1>
            <img src="<?= PLANTILLA ?>assets/img/logo2.png" height="30px" alt="Logo principal de Happy Memories">
          </div>

        </div>
        <div class="card-body mt-5">
          <div class="row">
            <div class="mb-3 col-lg-6">
              <label for="" class="form-label">Nombre Completo</label>

              <input type="text" class="form-control" required>


            </div>

            <div class="mb-3 col-lg-6">
              <label for="" class="form-label">Correo Electronico</label>

              <input type="text" class="form-control" required>


            </div>

            <div class="mb-3 col-lg-12">
              <label for="" class="form-label">Mensaje</label>

              <textarea class="form-control" rows="5" name="" id="" required></textarea>


            </div>

            <div class="mb-3 col-lg-12 align-items-center">
              

            <button type="submit" class="btn btn-primary"><i class="fa-solid fa-plus"></i> Enviar</button>


            </div>

          </div>




        </div>






      </div>
    </div><!-- Fin Servicios -->









  </section>

</main>

<script>


  console.log("aqui van a ir para cargar los eventos");
  var servicio = JSON.parse('<?= $this->servicio ?>');
  console.log(servicio);


  var datosCards = [
    { titulo: "Card 1", contenido: "Contenido de la Card 1" },
    { titulo: "Card 2", contenido: "Contenido de la Card 2" },
    { titulo: "Card 3", contenido: "Contenido de la Card 3" }
  ];
  var $contenedorCards = $("#contenedor-cards");

  function agregarCard(tipo, descripcion, precio, imagen,marca) {
    var $card = $("<div class='col-md-3 mb-4 col-lg-3'>" +
      "<div class='card'>" +

      "<img class='card-img-top' style='width: 100%; height: 200px; object-fit: cover; object-position: center;' src='<?= PLANTILLA ?>assets/img/" + imagen + "' alt='Servicios que se brindan'>" +
      "<div class='card-body'>" +
      "<h5 class='card-title'>Producto: " + tipo + "</h5>" +
      "<p class='card-text' style='text-align: justify;'><b> Marca: </b> " + marca + "<br> <b><b> Descripcion: </b> " + descripcion + "<br> <b> Precio del servicio: </b> " + precio + "</p>" +
      "<center> <a href='https://wa.me/+50588888888' target='_blank'> <button style='background-color: #17a2b8; border-color: #17a2b8;' type='button' class='btn btn-primary btn-sm float-right' ><span class='fa fa-cart-shopping'></span> Comprar</button></a> </center>"+
      
      "</div>" +
      "</div>" +
      "</div>");

    $contenedorCards.append($card);
  }


  for (i = 0; i < servicio.length; i++) {
    tipo = servicio[i]['nombre_producto'];
    descripcion = servicio[i]['descripcion'];
    precio = servicio[i]['precio'];
    imagen = servicio[i]['imagen'];
     marca = servicio[i]['marca'];

    agregarCard(tipo, descripcion, precio, imagen,marca);
  }


 

</script>