<main id="main" class="main">

    <div class="pagetitle">
        <h1>HappyMemories</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?= BASE_URL ?>" index>Home</a></li>
                <li class="breadcrumb-item active">Servicios</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
        <div class="row">
            <div class="card">
                <div class="card-header">
                    <center>
                        <h4 class="card-header">Realizar Respaldo Completo de la BD</h4>
                    </center>



                </div>
                <div class="card-body mt-5">

                    <!-- Button RESPALDO  -->
                  

                    <center>
                        <a id="generarcertif" href="respaldo/respaldo" class="btn btn-primary">
                        <i class="fa-solid fa-database"></i>
                        Realizar Respaldo de la BD

                        </a>
                    </center>
                </div>

            </div>
        </div>
        </div>

    </section>












</main>