<main id="main" class="main">

    <div class="pagetitle">
        <h1>HappyMemories</h1>
        <nav>
            <ol class="breadcrumb">
<li class="breadcrumb-item"><a href="<?= BASE_URL ?>"index>Home</a></li>                <li class="breadcrumb-item active">Propietario</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
        <div class="row">
            <div class="card">
                <div class="card-header">
                    <center>
                        <h4 class="card-header">Registro y Listado de Propietario</h4>
                    </center>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end pt-3">
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                            data-bs-target="#modalAgregarPropietario">
                            <i class="fa-solid fa-plus"></i> Agregar Nuevo
                        </button>
                    </div>

 
                </div>
                <div class="card-body mt-5">

                    <table id="table" class="display">
                        <thead>
                            <th>ID Propietario</th>
                            <th>Nombre</th>
                            
                           

                            <th>Acción</th>
                        </thead>
                        <tbody>
                            <?= $this->tabla ?>
                        </tbody>

                    </table>

                </div>
            </div>
        </div>

    </section>




    <!-- Modal  para agregar Municipio-->
    <div class="modal fade" id="modalAgregarPropietario" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header" style="background-color:#ecc006">
                    <h1 class="modal-title fs-5" style="font-weight:bold;color:white;" id="exampleModalLabel">Agregar datos de propietario</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <form class="row" method="post" id="agregarPropietario" enctype="multipart/form-data">

                        

                           
                            

                            <div class="mb-3 col-lg-12">
                                <label for="" class="form-label">Nombre Propietario</label>
                                <input type="text" class="form-control" id="nombre" name="nombre" required>
                            </div>

                    </div>






                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal"><i class="fa-solid fa-ban"></i> Cancelar</button>
                    <button style="color:#fff" type="submit" class="btn btn-success"><i class="fa-solid fa-plus"></i> Agregar Registro</button>
                </div>

                </form>
            </div>
        </div>
    </div>

      <!-- Modal  para agregar Municipio-->
    

</main>