<main id="main" class="main">

    <div class="pagetitle">
        <h1>HappyMemories</h1>
        <nav>
            <ol class="breadcrumb">
<li class="breadcrumb-item"><a href="<?= BASE_URL ?>"index>Home</a></li>                <li class="breadcrumb-item active">Cementerio</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
        <div class="row">
            <div class="card"> 
                <div class="card-header">
                    <center>
                        <h4 class="card-header ">Registro y Listado de Cementerio</h4>
                    </center>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end pt-3">
                    <a href="<?=BASE_URL?>cementerio/agregar"  class="btn btn-primary float-right">
                        <span class="fa fa-plus"></span>
                        Agregar nuevo
			        </a> 
                    </div>
                    
                   
                </div>
                <div class="card-body mt-5">
                
                    <table id="table" class="display">
                        <thead>
                            <th>ID Cementerio</th>
                            <th>Nombre Cementerio</th>
                            <th>municipio</th>
                            <th>Latitud</th>
                            <th>Longitud</th>
                            <th>Capacidad</th>
                            <th>Tipo</th>
                            <th>Hora Apertura</th>
                            <th>Hora Cierra</th>
                            <th>Acción</th>
                        </thead>
                        <tbody>
                            <?= $this->tabla ?>
                        </tbody>

                    </table>
                    
                </div>
            </div>
        </div>

    </section>

</main>